---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    vars:
      ansible_python_interpreter: /usr/bin/python3
    apt:
      update_cache: yes
     

  - name: Install tmux package
    vars:
      ansible_python_interpreter: /usr/bin/python3
    apt:
      name: tmux
